version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6500:5432"
    volumes:
      - ./postgresDB:/data/postgres/
    env_file:
      - ./app.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password123
    env_file:
      - ./app.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  posgresDB:
